default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shipments_tracking_development

test:
  <<: *default
  database: shipments_tracking_test

production:
  <<: *default
  database: shipments_tracking_production
  username: shipments_tracking
  password: <%= ENV['SHIPMENTS_TRACKING_DATABASE_PASSWORD'] %>
